
// Auth types

export const USER_LOGIN_SUCCESS='USER_LOGIN_SUCCESS'
export const USER_LOGIN_START='USER_LOGIN_START'
export const USER_LOGIN_FAILED='USER_LOGIN_FAILED'
export const USER_REGIST_SUCCESS='USER_REGIST_SUCCESS'
export const USER_REGIST_START='USER_REGIST_START'
export const USER_REGIST_FAILED='USER_REGIST_FAILED'
export const COUNT_CART='COUNT_CART'
export const USER_CHANGE_PASS_FAILED='USER_REGIST_FAILED'
export const USER_CHANGE_PASS_SUCCESS='USER_CHANGE_PASS_SUCCESS'
export const USER_CHANGE_PASS_START='USER_CHANGE_PASS_START'

// export const KEEP_LOGIN='KEEP_LOGIN'

// Auth